# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180922_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='related_list',
            new_name='list',
        ),
    ]
